from src.validators.tlc_validator import (
    _autogenerate_cfg,
    _extract_constant_names,
)


def test_extract_constant_names_handles_multiline_comment_annotated_blocks():
    spec = r"""---- MODULE PrisonersMini ----
EXTENDS Naturals, FiniteSets

CONSTANTS
  Prisoner,
    (*************************************************************************)
    (* The set of all prisoners.                                            *)
    (*************************************************************************)
  Counter
    (*************************************************************************)
    (* Distinguished counter prisoner.                                      *)
    (*************************************************************************)

VARIABLE x
vars == <<x>>
Init == x = 0
Next == UNCHANGED x
Spec == Init /\ [][Next]_vars
TypeOK == x \in 0..1
====
"""

    assert _extract_constant_names(spec) == ["Prisoner", "Counter"]


def test_autogenerated_cfg_infers_member_constant_as_singleton_model_value():
    spec = r"""---- MODULE PrisonersMini ----
EXTENDS Naturals, FiniteSets

CONSTANTS
  Prisoner,
  Counter

ASSUME /\ Counter \in Prisoner
       /\ Cardinality(Prisoner) > 1

VARIABLE x
vars == <<x>>
Init == x = 0
Next == UNCHANGED x
Spec == Init /\ [][Next]_vars
TypeOK == x \in 0..1
====
"""

    cfg = _autogenerate_cfg(spec)

    assert cfg is not None
    assert "CONSTANT Prisoner = {v1, v2, v3}" in cfg
    assert "CONSTANT Counter = v1" in cfg


def test_autogenerated_cfg_infers_numeric_nat_membership_constant() -> None:
    spec = r"""---- MODULE DieHarderMini ----
EXTENDS Naturals, FiniteSets

CONSTANT Goal

ASSUME Goal \in Nat

VARIABLE x
vars == <<x>>
Init == x = 0
Next == UNCHANGED x
Spec == Init /\ [][Next]_vars
TypeOK == x \in 0..1
====
"""

    cfg = _autogenerate_cfg(spec)

    assert cfg is not None
    assert "CONSTANT Goal = 3" in cfg
