import shutil

import pytest

from src.validators.tlc_validator import (
    _DEFAULT_JAR,
    _autogenerate_cfg,
    _extract_declared_property_names,
    _extract_static_action_names,
    validate_string,
)


LIVENESS_SPEC = r"""---- MODULE LivenessFails ----
EXTENDS Naturals, TLC
VARIABLES x
vars == <<x>>
Init == x = 0
Next == UNCHANGED x
Spec == Init /\ [][Next]_vars
TypeOK == x \in 0..1
EventuallyOne == <> (x = 1)
====
"""


def test_autogenerated_cfg_checks_declared_liveness_property():
    cfg = _autogenerate_cfg(LIVENESS_SPEC)

    assert cfg is not None
    assert "SPECIFICATION Spec" in cfg
    assert "INVARIANT TypeOK" in cfg
    assert "PROPERTY EventuallyOne" in cfg


def test_declared_property_extractor_ignores_state_invariants():
    assert _extract_declared_property_names(LIVENESS_SPEC) == ["EventuallyOne"]


def test_declared_property_extractor_ignores_tuple_and_sequence_delimiters():
    spec = r"""---- MODULE TupleSyntax ----
EXTENDS Sequences
VARIABLES x, q
vars == <<x, q>>
Init == /\ x = 0
        /\ q = <<>>
Next == UNCHANGED <<x, q>>
P(p) == /\ q = <<>>
        /\ UNCHANGED <<x, q>>
Spec == Init /\ [][Next]_vars
TypeOK == TRUE
EventuallyOne == <> (x = 1)
====
"""

    assert _extract_declared_property_names(spec) == ["EventuallyOne"]


def test_static_action_extractor_finds_named_actions_in_next():
    spec = r"""---- MODULE ActionNames ----
VARIABLES pc
vars == <<pc>>
Init == pc = "idle"
Acquire(p) == /\ pc = "idle"
              /\ pc' = "holding"
Release == /\ pc = "holding"
           /\ pc' = "idle"
Next == (\E p \in 1..3 : Acquire(p)) \/ Release
TypeOK == pc \in {"idle", "holding"}
====
"""

    assert _extract_static_action_names(spec) == ["Acquire", "Release"]


def test_declared_failing_liveness_is_not_false_gold():
    if shutil.which("java") is None or not _DEFAULT_JAR.exists():
        pytest.skip("TLC jar or Java is unavailable")

    result = validate_string(LIVENESS_SPEC, module_name="LivenessFails", timeout=20)

    assert result.tier != "gold"
    assert result.semantic.properties_declared is True
    assert result.semantic.properties_checked == 1
    assert result.semantic.property_names == ["EventuallyOne"]
    assert "violated" in result.raw_output.lower()
