"""
convert_to_gguf.py — Convert merged ChatTLA model to GGUF for Ollama deployment.

After merge_lora.py produces outputs/merged_model/, this script:
1. Clones/updates llama.cpp (provides the conversion script)
2. Converts the HuggingFace model to GGUF Q4_K_M format
3. Creates an Ollama Modelfile pointing to the GGUF
4. Registers the model with local Ollama as "chattla:20b"

GGUF quantisation choice
------------------------
Q4_K_M used to be recommended, but recent llama.cpp releases no longer
support 4-bit formats.  Falling back to Q8_0 (roughly 16-18 GB, high quality)
for the time being.  If/when q4_k_m returns, the script will handle it again.

After this script, test the deployment with:
    ollama run chattla:20b "Write a TLA+ spec for mutual exclusion."

Usage
-----
    python -m src.inference.convert_to_gguf
    python -m src.inference.convert_to_gguf --quant Q8_0
    python -m src.inference.convert_to_gguf --no-ollama-register  # GGUF only
"""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

_REPO_ROOT    = Path(__file__).resolve().parents[2]
_MERGED_MODEL = _REPO_ROOT / "outputs" / "merged_model"
_GGUF_OUT_DIR = _REPO_ROOT / "outputs" / "gguf"
_LLAMA_CPP_DIR = _REPO_ROOT / "outputs" / "llama.cpp"


import datetime as _dt

MODELFILE_TEMPLATE = """\
# ChatTLA — Fine-tuned gpt-oss-20b for TLA+ specification generation
# Generated by src/inference/convert_to_gguf.py

FROM {gguf_path}

# Harmony prompt format
# =====================
# gpt-oss-20b was fine-tuned using the "harmony" prompt format:
#   <|start|>system<|message|>...<|end|>
#   <|start|>developer<|message|>...<|end|>
#   <|start|>user<|message|>...<|end|>
#   <|start|>assistant<|channel|>final<|message|>...<|return|>
#
# Key design decisions:
#   - Template ends with `<|start|>assistant{{ .Response }}`
#     (NOT `<|channel|>final<|message|>`). Ollama filters channel
#     tokens from displayed output; the model generates its own
#     channel header and Ollama hides the analysis channel.
#   - `Reasoning: low` minimises analysis-channel tokens.
#   - Stop token is `<|return|>` (200002), NOT `<|end|>` (200007).

TEMPLATE \"\"\"<|start|>system<|message|>You are ChatGPT, a large language model trained by OpenAI.
Knowledge cutoff: 2024-06
Current date: {current_date}

Reasoning: low

# Valid channels: analysis, commentary, final. Channel must be included for every message.<|end|>
<|start|>developer<|message|># Instructions

You are ChatTLA, an expert at writing verified TLA+ formal specifications.
When asked to write a TLA+ spec, follow these rules exactly:
1. Start the module with ---- MODULE <ModuleName> ----
2. End with ====
3. Include EXTENDS, VARIABLES, Init, Next, and Spec operators
4. Define Spec == Init /\\ [][Next]_vars (with vars == <<v1, v2, ...>>)
5. Output only valid TLA+ code. No markdown fences, no explanation outside the spec.

TLC runtime rules (your spec MUST pass the TLC model checker):
6. CONSTANTS must be finite and enumerable. Never use \\in Nat or \\in Int unbounded — always use bounded ranges like 0..N where N is a CONSTANT.
7. Every disjunct in Next must specify ALL variables: either prime them (x' = ...) or use UNCHANGED <<x>>. A partial UNCHANGED causes TLC errors.
8. Init must assign every variable a concrete finite value. Never leave a variable unconstrained.
9. TypeOK must be an invariant that constrains every variable to a finite set (e.g., x \\in 0..N, state \\in {"idle", "active"}).
10. Avoid deadlock: if the system can terminate, add a Terminating == /\\ UNCHANGED vars disjunct to Next.

Critical TLA+ syntax rules:
- EXTENDS Integers for Int, +, -, *, \\div
- EXTENDS Sequences for Seq, Append, Len, Head, Tail
- EXTENDS FiniteSets for Cardinality, IsFiniteSet
- Declare ALL state variables in a VARIABLES line
- Use = (not ==) inside Init and Next conjuncts: /\\ x = value
- Function construction: [x \\in S |-> expr]  (NOT [x \\in S : expr])
- Do NOT use PlusCal syntax (:=, --algorithm, labels, while, goto)
- TypeOK must be defined if referenced as INVARIANT

<|end|>
<|start|>user<|message|>{{ .Prompt }}<|end|>
<|start|>assistant{{ .Response }}\"\"\"

PARAMETER temperature 0.3
PARAMETER num_ctx 4096
PARAMETER repeat_penalty 1.3
PARAMETER repeat_last_n 256
PARAMETER top_k 40
PARAMETER top_p 0.9
PARAMETER stop "<|return|>"
"""


def ensure_llama_cpp() -> Path:
    """Clone or update llama.cpp to get the conversion script."""
    if _LLAMA_CPP_DIR.exists():
        print("[convert_gguf] Updating llama.cpp...")
        subprocess.run(["git", "-C", str(_LLAMA_CPP_DIR), "pull", "--quiet"], check=True)
    else:
        print("[convert_gguf] Cloning llama.cpp...")
        subprocess.run([
            "git", "clone", "--depth=1",
            "https://github.com/ggerganov/llama.cpp",
            str(_LLAMA_CPP_DIR),
        ], check=True)

    convert_script = _LLAMA_CPP_DIR / "convert_hf_to_gguf.py"
    if not convert_script.exists():
        # Older llama.cpp uses convert.py
        convert_script = _LLAMA_CPP_DIR / "convert.py"
    if not convert_script.exists():
        raise FileNotFoundError(f"convert script not found in {_LLAMA_CPP_DIR}")

    # Install llama.cpp Python dependencies
    subprocess.run([sys.executable, "-m", "pip", "install", "-q", "gguf", "sentencepiece"], check=True)
    return convert_script


def convert_to_gguf(quant: str = "Q8_0") -> Path:
    """
    Convert the merged HuggingFace model to GGUF.

    Parameters
    ----------
    quant : str   Quantisation type: Q8_0 (default), F16, BF16, or any
                   value accepted by the llama.cpp converter (q8_0/tq1_0/tq2_0/auto).
                   The historical Q4_K_M label will be remapped to q8_0 with a warning.

    Returns
    -------
    Path to the produced .gguf file.
    """
    if not _MERGED_MODEL.exists():
        print(f"[convert_gguf] ERROR: Merged model not found at {_MERGED_MODEL}")
        print("[convert_gguf] Run `python -m src.training.merge_lora` first.")
        sys.exit(1)

    convert_script = ensure_llama_cpp()
    _GGUF_OUT_DIR.mkdir(parents=True, exist_ok=True)

    gguf_path = _GGUF_OUT_DIR / f"chattla-20b-{quant}.gguf"

    print(f"[convert_gguf] Converting to GGUF ({quant})...")
    # llama.cpp convert script expects a limited set of outtypes; map our
    # human-friendly quant names accordingly.
    outtype = quant.lower()
    if outtype == "q4_k_m":
        # newer versions of llama.cpp dropped q4_k_m; fall back to q4_0
        print("[convert_gguf] WARNING: q4_k_m unsupported by llama.cpp, using q4_0 instead")
        outtype = "q4_0"
    cmd = [
        sys.executable, str(convert_script),
        str(_MERGED_MODEL),
        "--outfile", str(gguf_path),
        "--outtype", outtype,
    ]
    subprocess.run(cmd, check=True)
    print(f"[convert_gguf] GGUF written → {gguf_path}  ({gguf_path.stat().st_size / 1e9:.1f} GB)")
    return gguf_path


def register_with_ollama(gguf_path: Path, model_name: str = "chattla:20b") -> None:
    """Register the GGUF with the local Ollama daemon via 'ollama create'."""
    modelfile_path = gguf_path.parent / "Modelfile"
    # Use .replace() instead of .format() — the template contains TLA+ examples
    # like {"idle", "active"} which str.format() misinterprets as placeholders.
    rendered = (
        MODELFILE_TEMPLATE
        .replace("{gguf_path}", str(gguf_path))
        .replace("{current_date}", _dt.date.today().isoformat())
    )
    modelfile_path.write_text(rendered, encoding="utf-8")
    print(f"[convert_gguf] Modelfile written → {modelfile_path}")

    print(f"[convert_gguf] Registering with Ollama as '{model_name}'...")
    subprocess.run([
        "ollama", "create", model_name,
        "-f", str(modelfile_path),
    ], check=True)
    print(f"[convert_gguf] Success! Test with: ollama run {model_name}")


def main(quant: str = "Q8_0", register: bool = True, model_name: str = "chattla:20b") -> None:
    gguf_path = convert_to_gguf(quant=quant)

    if register:
        register_with_ollama(gguf_path, model_name=model_name)


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Convert merged ChatTLA model to GGUF for Ollama")
    parser.add_argument("--quant",             default="Q8_0", help="Quantisation level (default: Q8_0)")
    parser.add_argument("--no-ollama-register", action="store_true", help="Skip 'ollama create' step")
    parser.add_argument("--model-name",         default="chattla:20b", help="Ollama model tag")
    args = parser.parse_args()

    main(quant=args.quant, register=not args.no_ollama_register, model_name=args.model_name)
