"""
convert_to_gguf.py — Convert merged ChatTLA model to GGUF for Ollama deployment.

After merge_lora.py produces outputs/merged_model/, this script:
1. Clones/updates llama.cpp (provides the conversion script)
2. Converts the HuggingFace model to GGUF Q4_K_M format
3. Creates an Ollama Modelfile pointing to the GGUF
4. Registers the model with local Ollama as "chattla:20b"

GGUF quantisation choice
------------------------
Q4_K_M is recommended:
  - Memory: ~8.5 GB for a 20B model (fits comfortably in 49 GB GPU)
  - Quality: near-equivalent to F16 on code tasks; minimal regression vs BF16
  - Q8_0 also built as a "lossless" variant for ablation studies

After this script, test the deployment with:
    ollama run chattla:20b "Write a TLA+ spec for mutual exclusion."

Usage
-----
    python -m src.inference.convert_to_gguf
    python -m src.inference.convert_to_gguf --quant Q8_0
    python -m src.inference.convert_to_gguf --no-ollama-register  # GGUF only
"""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

_REPO_ROOT    = Path(__file__).resolve().parents[2]
_MERGED_MODEL = _REPO_ROOT / "outputs" / "merged_model"
_GGUF_OUT_DIR = _REPO_ROOT / "outputs" / "gguf"
_LLAMA_CPP_DIR = _REPO_ROOT / "outputs" / "llama.cpp"


MODELFILE_TEMPLATE = """\
# ChatTLA — Fine-tuned gpt-oss-20b for TLA+ specification generation
# Generated by src/inference/convert_to_gguf.py

FROM {gguf_path}

SYSTEM \"\"\"
You are ChatTLA, an expert at writing verified TLA+ formal specifications.
When asked to write a TLA+ spec, follow these rules exactly:
1. Start the module with ---- MODULE <ModuleName> ----
2. End with ====
3. Include EXTENDS, VARIABLES, Init, Next, and Spec operators
4. After the TLA+ module, append a TLC configuration block:
   SPECIFICATION Spec
   INVARIANT TypeOK   (if TypeOK is defined)
5. Output only valid TLA+ code. No markdown fences, no explanation outside the spec.
\"\"\"

PARAMETER temperature 0.2
PARAMETER num_ctx 4096
"""


def ensure_llama_cpp() -> Path:
    """Clone or update llama.cpp to get the conversion script."""
    if _LLAMA_CPP_DIR.exists():
        print("[convert_gguf] Updating llama.cpp...")
        subprocess.run(["git", "-C", str(_LLAMA_CPP_DIR), "pull", "--quiet"], check=True)
    else:
        print("[convert_gguf] Cloning llama.cpp...")
        subprocess.run([
            "git", "clone", "--depth=1",
            "https://github.com/ggerganov/llama.cpp",
            str(_LLAMA_CPP_DIR),
        ], check=True)

    convert_script = _LLAMA_CPP_DIR / "convert_hf_to_gguf.py"
    if not convert_script.exists():
        # Older llama.cpp uses convert.py
        convert_script = _LLAMA_CPP_DIR / "convert.py"
    if not convert_script.exists():
        raise FileNotFoundError(f"convert script not found in {_LLAMA_CPP_DIR}")

    # Install llama.cpp Python dependencies
    subprocess.run([sys.executable, "-m", "pip", "install", "-q", "gguf", "sentencepiece"], check=True)
    return convert_script


def convert_to_gguf(quant: str = "Q4_K_M") -> Path:
    """
    Convert the merged HuggingFace model to GGUF.

    Parameters
    ----------
    quant : str   Quantisation type: Q4_K_M (default), Q8_0, F16, etc.

    Returns
    -------
    Path to the produced .gguf file.
    """
    if not _MERGED_MODEL.exists():
        print(f"[convert_gguf] ERROR: Merged model not found at {_MERGED_MODEL}")
        print("[convert_gguf] Run `python -m src.training.merge_lora` first.")
        sys.exit(1)

    convert_script = ensure_llama_cpp()
    _GGUF_OUT_DIR.mkdir(parents=True, exist_ok=True)

    gguf_path = _GGUF_OUT_DIR / f"chattla-20b-{quant}.gguf"

    print(f"[convert_gguf] Converting to GGUF ({quant})...")
    cmd = [
        sys.executable, str(convert_script),
        str(_MERGED_MODEL),
        "--outfile", str(gguf_path),
        "--outtype", quant.lower(),
    ]
    subprocess.run(cmd, check=True)
    print(f"[convert_gguf] GGUF written → {gguf_path}  ({gguf_path.stat().st_size / 1e9:.1f} GB)")
    return gguf_path


def register_with_ollama(gguf_path: Path, model_name: str = "chattla:20b") -> None:
    """Register the GGUF with the local Ollama daemon via 'ollama create'."""
    modelfile_path = gguf_path.parent / "Modelfile"
    modelfile_path.write_text(
        MODELFILE_TEMPLATE.format(gguf_path=str(gguf_path)),
        encoding="utf-8",
    )
    print(f"[convert_gguf] Modelfile written → {modelfile_path}")

    print(f"[convert_gguf] Registering with Ollama as '{model_name}'...")
    subprocess.run([
        "ollama", "create", model_name,
        "-f", str(modelfile_path),
    ], check=True)
    print(f"[convert_gguf] Success! Test with: ollama run {model_name}")


def main(quant: str = "Q4_K_M", register: bool = True, model_name: str = "chattla:20b") -> None:
    gguf_path = convert_to_gguf(quant=quant)

    # Also build Q8_0 for ablation
    if quant == "Q4_K_M":
        print("[convert_gguf] Also building Q8_0 for ablation comparison...")
        convert_to_gguf(quant="Q8_0")

    if register:
        register_with_ollama(gguf_path, model_name=model_name)


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Convert merged ChatTLA model to GGUF for Ollama")
    parser.add_argument("--quant",             default="Q4_K_M", help="Quantisation level (default: Q4_K_M)")
    parser.add_argument("--no-ollama-register", action="store_true", help="Skip 'ollama create' step")
    parser.add_argument("--model-name",         default="chattla:20b", help="Ollama model tag")
    args = parser.parse_args()

    main(quant=args.quant, register=not args.no_ollama_register, model_name=args.model_name)
