"""
tlc_validator.py — Wrapper around the TLA+ TLC model checker.

TLC is the primary quality gate for training data.  Running a spec through
TLC and getting no violations makes it "gold tier" — the strongest signal
that the spec is semantically meaningful, not just syntactically valid.

Validation tiers
----------------
gold   — TLC runs to completion with zero violations
silver — SANY parse succeeds but TLC can't run (missing cfg, infinite state, etc.)
bronze — SANY fails (syntactically invalid TLA+); still archived for analysis

.cfg handling
-------------
Many scraped specs lack a companion .cfg file.  TLC requires at minimum:
    INIT  Init
    NEXT  Next
We auto-generate a minimal cfg from common patterns if none is provided.
The auto-generation heuristic looks for `Init` and `Next` definitions and
attempts to add `INVARIANT TypeOK` if a `TypeOK` operator is defined.

Research note
-------------
TLC's exit codes are NOT reliable across versions.  We parse stdout instead:
  - "Model checking completed" with "No error" = gold
  - "Error:" or "Invariant ... is violated" = violation found (still bronze)
  - TLC timeout / state explosion = treated as silver (SANY already passed)
"""

from __future__ import annotations

import re
import subprocess
import tempfile
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

from .sany_validator import validate_file as sany_validate_file, _TLA_TOOLS_JAR

_DEFAULT_JAR = _TLA_TOOLS_JAR
# Default TLC timeout per spec in seconds.  Most well-formed specs finish in <30s.
# Large state-space specs can run forever — we cap them and call it silver.
_TLC_TIMEOUT_S = 60


@dataclass
class SemanticInfo:
    """Semantic quality signals beyond pass/fail."""
    # Coverage: fraction of Next sub-actions that generate at least 1 state
    action_coverage: float = 0.0         # 0.0–1.0; 1.0 = all actions reachable
    total_actions: int = 0
    dead_actions: list[str] = field(default_factory=list)  # action names with 0 states
    # State space
    distinct_states: int = 0
    total_states: int = 0
    # Invariant effectiveness: does the spec actually constrain behaviour?
    invariant_names: list[str] = field(default_factory=list)
    invariants_checked: int = 0          # how many INVARIANTs TLC actually checked
    trivial_invariant: bool = False      # TRUE if invariant is vacuously true (e.g. TRUE, TypeOK on empty state)
    # Mutation test: did weakening the spec change TLC's outcome?
    mutation_tested: bool = False
    mutation_caught: bool = False        # TRUE = invariant caught the mutation → semantically meaningful
    # Per-component verdicts (DeepSeek-Prover-V2 inspired denser reward signal).
    # Populated for every TLCResult — including silver and bronze — so the
    # training loop can reward partial progress instead of all-or-nothing.
    init_present: bool = False
    next_present: bool = False
    init_level_ok: bool = False
    next_level_ok: bool = False
    invariants_declared: bool = False
    tlc_depth1_ok: bool = False
    tlc_full_ok: bool = False
    partial_credit: float = 0.0          # weighted mean of the verdicts above ∈ [0, 1]

    def is_diamond(self) -> bool:
        """Diamond tier: semantically meaningful spec, not just syntactically valid.

        Requires ALL of:
          1. distinct_states > 1    — non-trivial state space (not a single-state spec)
          2. not trivial_invariant  — invariant isn't vacuously TRUE
          3. invariants_checked > 0 — at least one invariant is declared and checked
          4. mutation_caught        — removing invariants changes TLC outcome
                                      (proves invariants actually constrain behavior)

        Notably we do NOT require action_coverage == 1.0: partial coverage
        is fine as long as the spec is semantically constrained.
        """
        return (
            self.distinct_states > 1
            and not self.trivial_invariant
            and self.invariants_checked > 0
            and self.mutation_tested
            and self.mutation_caught
        )


@dataclass
class TLCResult:
    """Full result of a TLC model-check attempt."""
    tier: str                    # "gold" | "silver" | "bronze"
    sany_errors: list[str] = field(default_factory=list)
    tlc_violations: list[str] = field(default_factory=list)
    raw_output: str = ""
    runtime_seconds: float = 0.0
    cfg_was_autogenerated: bool = False
    tla_file: str = ""
    semantic: SemanticInfo = field(default_factory=SemanticInfo)

    @property
    def is_diamond(self) -> bool:
        """True if this spec passes both TLC gold AND the Diamond semantic gate."""
        return self.tier == "gold" and self.semantic.is_diamond()


def validate_file(
    tla_path: Path,
    cfg_path: Optional[Path] = None,
    jar: Path = _DEFAULT_JAR,
    timeout: int = _TLC_TIMEOUT_S,
) -> TLCResult:
    """
    Run TLC on a .tla + optional .cfg file pair.

    Parameters
    ----------
    tla_path : Path            Path to the .tla spec file.
    cfg_path : Path | None     Path to .cfg; auto-generated if None.
    jar      : Path            Path to tla2tools.jar.
    timeout  : int             Seconds before we kill TLC and call it silver.

    Returns
    -------
    TLCResult describing the validation outcome.
    """
    import time

    if not jar.exists():
        raise FileNotFoundError(f"tla2tools.jar not found at {jar}")

    # --- Step 1: SANY check first (fast) ------------------------------------
    sany_result = sany_validate_file(tla_path, jar=jar)
    if not sany_result.valid:
        # Bronze: SANY refused the spec. partial_credit stays at 0 because
        # _ast_verdicts won't be able to parse it either, but we still call
        # the helper so the verdict fields are populated (all False).
        bronze_semantic = SemanticInfo()
        try:
            tla_text = tla_path.read_text(encoding="utf-8", errors="replace")
            mod_match = re.search(r"MODULE\s+(\w+)", tla_text)
            mod_name = mod_match.group(1) if mod_match else "Temp"
            _populate_component_verdicts(
                bronze_semantic, tla_text, "", mod_name, jar,
                full_tlc_passed=False, run_depth1=False,
            )
        except Exception:
            pass
        return TLCResult(
            tier="bronze",
            sany_errors=sany_result.errors,
            raw_output=sany_result.raw_output,
            tla_file=str(tla_path),
            semantic=bronze_semantic,
        )

    # --- Step 2: Resolve or generate .cfg -----------------------------------
    cfg_was_autogenerated = False
    if cfg_path is None or not cfg_path.exists():
        tla_content = tla_path.read_text(encoding="utf-8", errors="replace")
        cfg_text = _autogenerate_cfg(tla_content)
        if cfg_text is None:
            # Can't even guess Init/Next — return silver (SANY passed).
            # Component verdicts still useful: SANY succeeded so init_present /
            # next_present / level checks may report partial structure.
            silver_semantic = SemanticInfo()
            try:
                mod_match = re.search(r"MODULE\s+(\w+)", tla_content)
                mod_name = mod_match.group(1) if mod_match else "Temp"
                _populate_component_verdicts(
                    silver_semantic, tla_content, "", mod_name, jar,
                    full_tlc_passed=False, run_depth1=False,
                )
            except Exception:
                pass
            return TLCResult(
                tier="silver",
                raw_output="No .cfg and could not auto-generate one (Init/Next not found).",
                tla_file=str(tla_path),
                semantic=silver_semantic,
            )
        cfg_was_autogenerated = True
        # Write auto-cfg next to the tla file so TLC can find it
        cfg_path = tla_path.with_suffix(".cfg")
        cfg_path.write_text(cfg_text, encoding="utf-8")

    # --- Step 3: Run TLC ----------------------------------------------------
    cmd = [
        "java", "-cp", str(jar),
        "tlc2.TLC",
        "-config", str(cfg_path),
        str(tla_path),
    ]
    t0 = time.monotonic()
    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=timeout,
            cwd=tla_path.parent,  # TLC resolves EXTENDS relative to cwd
        )
        elapsed = time.monotonic() - t0
        stdout = result.stdout + result.stderr
        violations = _parse_violations(stdout)

        if violations:
            # SANY already passed (step 1); TLC found semantic issues → silver
            tier = "silver"
        elif _detect_success(stdout):
            tier = "gold"
        else:
            # TLC ran but inconclusive (infinite state space, partial check)
            tier = "silver"

        # Compute semantic quality signals.
        # Mutation/coverage stats only meaningful when the full TLC run
        # succeeded; component verdicts are computed for every tier so the
        # training loop sees a non-zero reward gradient on near-misses.
        semantic = SemanticInfo()
        tla_text = tla_path.read_text(encoding="utf-8", errors="replace")
        cfg_text = cfg_path.read_text(encoding="utf-8", errors="replace") if cfg_path else ""
        mod_match = re.search(r"MODULE\s+(\w+)", tla_text)
        mod_name = mod_match.group(1) if mod_match else "Temp"
        if tier == "gold":
            try:
                semantic = compute_semantic_info(
                    tla_text, cfg_text, stdout,
                    module_name=mod_name, jar=jar,
                    mutation_timeout=min(timeout, 30),
                )
            except Exception:
                pass  # semantic analysis is best-effort
        try:
            _populate_component_verdicts(
                semantic, tla_text, cfg_text, mod_name, jar,
                full_tlc_passed=(tier == "gold"),
            )
        except Exception:
            pass

        return TLCResult(
            tier=tier,
            tlc_violations=violations,
            raw_output=stdout,
            runtime_seconds=elapsed,
            cfg_was_autogenerated=cfg_was_autogenerated,
            tla_file=str(tla_path),
            semantic=semantic,
        )

    except subprocess.TimeoutExpired:
        timeout_semantic = SemanticInfo()
        try:
            tla_text = tla_path.read_text(encoding="utf-8", errors="replace")
            cfg_text_to = cfg_path.read_text(encoding="utf-8", errors="replace") if cfg_path else ""
            mod_match = re.search(r"MODULE\s+(\w+)", tla_text)
            mod_name = mod_match.group(1) if mod_match else "Temp"
            _populate_component_verdicts(
                timeout_semantic, tla_text, cfg_text_to, mod_name, jar,
                full_tlc_passed=False, run_depth1=True,
            )
        except Exception:
            pass
        return TLCResult(
            tier="silver",
            raw_output=f"TLC timed out after {timeout}s (state space likely too large).",
            runtime_seconds=float(timeout),
            cfg_was_autogenerated=cfg_was_autogenerated,
            tla_file=str(tla_path),
            semantic=timeout_semantic,
        )


def _extract_inline_cfg(tla_content: str) -> tuple[str, Optional[str]]:
    """Extract TLC config lines appended after ==== in the spec.

    Many model outputs include config directives (SPECIFICATION, INVARIANT,
    CONSTANT) after the module closing delimiter.  Previously these were
    preserved in the spec text but never passed to TLC as a .cfg, so the
    validator always fell back to heuristic autogeneration.

    Returns (clean_tla, cfg_text_or_None).
    """
    m = re.search(r"(----\s*MODULE\b.*?={4,})(.*)", tla_content, re.DOTALL)
    if not m:
        return tla_content, None

    module_part = m.group(1)
    after_module = m.group(2).strip()
    if not after_module:
        return tla_content, None

    _CFG_KEYWORDS = {
        "SPECIFICATION", "INIT", "NEXT", "INVARIANT", "INVARIANTS",
        "PROPERTY", "PROPERTIES", "CONSTANT", "CONSTANTS",
        "CONSTRAINT", "SYMMETRY", "VIEW",
    }
    cfg_lines = []
    for line in after_module.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("\\*"):
            continue
        first_word = stripped.split()[0].upper() if stripped.split() else ""
        if first_word in _CFG_KEYWORDS:
            cfg_lines.append(stripped)

    if cfg_lines:
        return module_part, "\n".join(cfg_lines) + "\n"
    return tla_content, None


def validate_string(
    tla_content: str,
    cfg_content: Optional[str] = None,
    module_name: str = "Temp",
    jar: Path = _DEFAULT_JAR,
    timeout: int = _TLC_TIMEOUT_S,
) -> TLCResult:
    """
    Run TLC on in-memory spec+cfg strings using a temp directory.

    If cfg_content is None, tries to extract an inline config block
    appended after ==== in the spec before falling back to autogeneration.
    """
    # Extract inline TLC config from after ==== if no explicit cfg provided
    if cfg_content is None:
        tla_content, inline_cfg = _extract_inline_cfg(tla_content)
        if inline_cfg:
            cfg_content = inline_cfg

    with tempfile.TemporaryDirectory() as tmpdir:
        tmp = Path(tmpdir)
        tla_path = tmp / f"{module_name}.tla"
        tla_path.write_text(tla_content, encoding="utf-8")
        cfg_path = None
        if cfg_content:
            cfg_path = tmp / f"{module_name}.cfg"
            cfg_path.write_text(cfg_content, encoding="utf-8")
        return validate_file(tla_path, cfg_path=cfg_path, jar=jar, timeout=timeout)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _detect_success(output: str) -> bool:
    """TLC prints 'Model checking completed. No error has been found.' on success."""
    return bool(re.search(r"no error has been found", output, re.IGNORECASE))


def _parse_violations(output: str) -> list[str]:
    """Extract violation/error messages from TLC output."""
    violations: list[str] = []
    for line in output.splitlines():
        stripped = line.strip()
        # Skip harmless / success lines
        if re.search(r"(Warning.*garbage collector|Warning.*UseParallelGC)", stripped, re.IGNORECASE):
            continue
        if re.search(r"no error has been found", stripped, re.IGNORECASE):
            continue
        if re.search(r"^(Finished|The depth|The average|calculated)", stripped):
            continue
        if re.search(r"(Invariant|Property|Error|violation|is violated)", stripped, re.IGNORECASE):
            violations.append(stripped)
    return violations


def _parse_coverage(output: str) -> tuple[int, list[str], int]:
    """Parse TLC coverage stats to find dead actions.

    TLC prints lines like:
      <Init line 10, col 1 to line 12, col 20 of module Foo>: 3:3
      <Next line 14, col 1 to line 20, col 30 of module Foo>: 15:100
      <Action1 line 22, col 3 to line 25, col 10 of module Foo>: 0:0

    The format is <name ...>: distinct:total
    An action with 0:0 or 0:N is dead (unreachable from Init via Next).

    Returns (total_actions, dead_action_names, distinct_states).
    """
    total_actions = 0
    dead: list[str] = []
    distinct_states = 0

    for line in output.splitlines():
        # Match coverage lines: <ActionName line ...>: N:M
        m = re.match(r"<(\w+)\s+line\s+\d+.*?>:\s*(\d+):(\d+)", line.strip())
        if m:
            name, distinct_str, total_str = m.group(1), m.group(2), m.group(3)
            if name in ("Init",):
                continue  # Init is always covered
            total_actions += 1
            d = int(distinct_str)
            if d == 0:
                dead.append(name)

    # Parse overall state count — use LAST match since TLC prints initial count
    # ("1 distinct state generated") before the final summary line
    # ("N states generated, M distinct states found").
    all_distinct = re.findall(r"(\d+)\s+distinct\s+state", output)
    if all_distinct:
        distinct_states = int(all_distinct[-1])

    return total_actions, dead, distinct_states


def _parse_state_counts(output: str) -> tuple[int, int]:
    """Extract distinct and total state counts from TLC output."""
    distinct = 0
    total = 0
    # Use last match — TLC prints "1 distinct state generated" for initial states
    # then "N states generated, M distinct states found" in the summary.
    all_distinct = re.findall(r"(\d+)\s+distinct\s+state", output)
    if all_distinct:
        distinct = int(all_distinct[-1])
    all_generated = re.findall(r"(\d+)\s+states?\s+generated", output)
    if all_generated:
        total = int(all_generated[-1])
    return distinct, total


def _extract_invariant_names(tla_content: str, cfg_content: str = "") -> list[str]:
    """Find invariant names from the cfg and spec."""
    names: list[str] = []
    # From cfg: INVARIANT Foo Bar
    for m in re.finditer(r"INVARIANTS?\s+(.+)", cfg_content):
        for name in re.split(r"\s+", m.group(1).strip()):
            if name and not name.startswith("\\*"):
                names.append(name)
    # Fallback: look for common invariant patterns in spec
    if not names:
        for m in re.finditer(r"^(\w+Inv(?:ariant)?|TypeOK|Safety\w*)\s*==", tla_content, re.MULTILINE):
            names.append(m.group(1))
    return names


def _check_trivial_invariant(tla_content: str, inv_names: list[str]) -> bool:
    """Detect obviously trivial invariants (e.g. 'TypeOK == TRUE')."""
    for name in inv_names:
        m = re.search(rf"^{re.escape(name)}\s*==\s*(.+?)$", tla_content, re.MULTILINE)
        if m:
            body = m.group(1).strip()
            # Trivially true
            if body in ("TRUE", "True", "true"):
                return True
    return False


def _mutation_test(
    tla_content: str,
    cfg_content: str,
    module_name: str,
    jar: Path,
    timeout: int = 30,
) -> tuple[bool, bool]:
    """Two-phase mutation test to verify invariants are semantically meaningful.

    Phase 1 (deadlock probe): Remove invariants from cfg AND switch
    SPECIFICATION → INIT/NEXT.  Disabling stuttering exposes terminal
    states as deadlocks — proving bounded, non-trivial state space.

    Phase 2 (invariant negation): Negate one non-TypeOK invariant in the
    TLA+ source (keep cfg unchanged).  If TLC reports a violation, the
    invariant rules out reachable states — it's not vacuously true.

    Returns (tested: bool, caught: bool).
    """
    had_invariants = any(
        re.match(r"\s*INVARIANTS?\s+", line)
        for line in cfg_content.splitlines()
    )
    if not had_invariants:
        return False, False

    # --- Phase 1: deadlock probe (remove invariants + use INIT/NEXT) ----------
    mutated_cfg_lines = []
    has_spec_line = False
    for line in cfg_content.splitlines():
        if re.match(r"\s*INVARIANTS?\s+", line):
            continue
        if re.match(r"\s*SPECIFICATION\s+", line):
            has_spec_line = True
            mutated_cfg_lines.append("INIT Init")
            mutated_cfg_lines.append("NEXT Next")
            continue
        mutated_cfg_lines.append(line)

    if has_spec_line:
        mutated_cfg = "\n".join(mutated_cfg_lines) + "\n"
        if _run_mutation(tla_content, mutated_cfg, module_name, jar, timeout):
            return True, True

    # --- Phase 2: invariant negation ------------------------------------------
    inv_names = _extract_invariant_names(tla_content, cfg_content)
    non_typeok = [n for n in inv_names if n != "TypeOK"]
    if not non_typeok:
        non_typeok = inv_names[:1]

    for inv_name in non_typeok:
        pattern = rf"^({re.escape(inv_name)}\s*==\s*)(.+?)$"
        m = re.search(pattern, tla_content, re.MULTILINE)
        if not m:
            continue
        original_line = m.group(0)
        body = m.group(2).strip()
        negated_line = f"{m.group(1)}~({body})"
        mutated_tla = tla_content.replace(original_line, negated_line, 1)
        if _run_mutation(mutated_tla, cfg_content, module_name, jar, timeout):
            return True, True

    return True, False


def _run_mutation(
    tla_content: str,
    cfg_content: str,
    module_name: str,
    jar: Path,
    timeout: int,
) -> bool:
    """Run TLC on a mutated spec/cfg and return True if the outcome changed."""
    with tempfile.TemporaryDirectory() as tmpdir:
        tmp = Path(tmpdir)
        tla_path = tmp / f"{module_name}.tla"
        cfg_path = tmp / f"{module_name}.cfg"
        tla_path.write_text(tla_content, encoding="utf-8")
        cfg_path.write_text(cfg_content, encoding="utf-8")

        cmd = [
            "java", "-cp", str(jar),
            "tlc2.TLC",
            "-config", str(cfg_path),
            str(tla_path),
        ]
        try:
            result = subprocess.run(
                cmd, capture_output=True, text=True, timeout=timeout, cwd=tmp,
            )
            stdout = result.stdout + result.stderr
            violations = _parse_violations(stdout)
            success = _detect_success(stdout)
            return bool(violations) or not success
        except (subprocess.TimeoutExpired, Exception):
            return False


def _populate_component_verdicts(
    semantic: SemanticInfo,
    tla_content: str,
    cfg_content: str,
    module_name: str,
    jar: Path,
    full_tlc_passed: bool,
    run_depth1: bool = True,
) -> None:
    """Run the per-component validator and copy fields onto SemanticInfo.

    Lives here so call sites in validate_file don't need to import the
    component_validator module conditionally. Failures are silently absorbed by
    the surrounding try/except blocks — partial credit defaults to 0.
    """
    from src.validators.component_validator import validate_components

    verdicts = validate_components(
        tla_content,
        cfg_content=cfg_content or None,
        module_name=module_name,
        jar=jar,
        full_tlc_passed=full_tlc_passed,
        run_depth1=run_depth1 and bool(cfg_content),
    )
    semantic.init_present = verdicts.init_present
    semantic.next_present = verdicts.next_present
    semantic.init_level_ok = verdicts.init_level_ok
    semantic.next_level_ok = verdicts.next_level_ok
    semantic.invariants_declared = verdicts.invariants_declared
    semantic.tlc_depth1_ok = verdicts.tlc_depth1_ok
    semantic.tlc_full_ok = verdicts.tlc_full_ok
    semantic.partial_credit = verdicts.partial_credit


def compute_semantic_info(
    tla_content: str,
    cfg_content: str,
    tlc_output: str,
    module_name: str = "Temp",
    jar: Path = _DEFAULT_JAR,
    run_mutation: bool = True,
    mutation_timeout: int = 30,
) -> SemanticInfo:
    """Compute semantic quality signals from a gold-tier TLC run."""
    info = SemanticInfo()

    # 1. Coverage / reachability
    total_actions, dead_actions, distinct_states = _parse_coverage(tlc_output)
    info.total_actions = total_actions
    info.dead_actions = dead_actions
    info.action_coverage = (
        (total_actions - len(dead_actions)) / total_actions
        if total_actions > 0 else 0.0
    )

    # 2. State space
    info.distinct_states, info.total_states = _parse_state_counts(tlc_output)

    # 3. Invariant analysis
    info.invariant_names = _extract_invariant_names(tla_content, cfg_content)
    info.invariants_checked = len(info.invariant_names)
    info.trivial_invariant = _check_trivial_invariant(tla_content, info.invariant_names)

    # 4. Mutation test (only for gold specs — silver/bronze already failed)
    if run_mutation and info.invariants_checked > 0 and not info.trivial_invariant:
        info.mutation_tested, info.mutation_caught = _mutation_test(
            tla_content, cfg_content, module_name, jar, timeout=mutation_timeout,
        )

    return info


def _extract_constant_names(tla_content: str) -> list[str]:
    """Extract all CONSTANT/CONSTANTS names from the spec, handling multiline declarations.

    Handles:
      CONSTANTS N, M, K
      CONSTANTS
        N,
        M,
        K
      CONSTANT N : Nat, M : Nat   (strips type annotations)
    """
    names: list[str] = []
    in_const_block = False

    for line in tla_content.splitlines():
        stripped = line.strip()
        if stripped.startswith("\\*") or stripped.startswith("(*"):
            continue

        # Start of a CONSTANT(S) declaration
        m = re.match(r"^CONSTANTS?\s*(.*)", stripped)
        if m:
            rest = m.group(1).strip()
            if rest:
                # Inline: CONSTANTS N, M, K  or  CONSTANTS N : Nat, M : Nat
                for part in rest.split(","):
                    # Take only the identifier, strip type annotations (: Nat)
                    ident = part.strip().split(":")[0].split("(")[0].strip().rstrip(",")
                    if ident and re.match(r"^[A-Za-z_]\w*$", ident):
                        names.append(ident)
                # Check if declaration continues (trailing comma)
                in_const_block = rest.rstrip().endswith(",")
            else:
                # Bare "CONSTANTS" with names on subsequent lines
                in_const_block = True
            continue

        if in_const_block:
            # Continuation line of a multiline CONSTANT block
            if not stripped or re.match(r"^(VARIABLE|ASSUME|----)", stripped):
                in_const_block = False
                continue
            for part in stripped.split(","):
                ident = part.strip().split(":")[0].split("(")[0].strip().rstrip(",")
                if ident and re.match(r"^[A-Za-z_]\w*$", ident):
                    names.append(ident)
            # Stop if no trailing comma
            if not stripped.rstrip().endswith(","):
                in_const_block = False

    return names


def _infer_constant_type(name: str, tla_content: str) -> str:
    """Infer the TLC assignment for a CONSTANT based on how it's used in the spec.

    Heuristics (checked in order):
      - Used as 1..Name or 0..Name → numeric (= 3)
      - Used as \\in Name → set of model values (= {v1, v2, v3})
      - Used as Name[i] or Name(x) → function, skip (let TLC decide)
      - Name matches known set patterns (Procs, Nodes, etc.) → model value set
      - Name matches known numeric patterns (N, M, MAX, etc.) → numeric
      - Default: numeric (= 3) — safest for small state spaces
    """
    # Check usage patterns in the spec
    # Pattern: 1..Name or 0..Name → numeric range bound
    if re.search(rf"\b\d+\s*\.\.\s*{re.escape(name)}\b", tla_content):
        return f"CONSTANT {name} = 3"

    # Pattern: \\in Name (used as a set to iterate over) → model value set
    if re.search(rf"\\in\s+{re.escape(name)}\b", tla_content):
        # Check if it's used with Cardinality or as a function domain
        if re.search(rf"Cardinality\s*\(\s*{re.escape(name)}\s*\)", tla_content):
            return f"CONSTANT {name} = {{v1, v2, v3}}"
        return f"CONSTANT {name} = {{v1, v2, v3}}"

    # Pattern: Name matches known set-of-actors names
    if re.match(r"^(Proc|Process|Node|Server|Client|Participant|"
                r"Thread|Worker|Acceptor|Proposer|Learner|Replica|"
                r"Philosopher|Fork)s?$", name):
        return f"CONSTANT {name} = {{v1, v2, v3}}"

    # Pattern: Name matches known coordinator/singleton
    if re.match(r"^(Coordinator|Leader|Primary|Head|Tail)$", name):
        return f"CONSTANT {name} = v1"

    # Pattern: Name matches known numeric bounds
    if re.match(r"^(N|M|K|MAX|Max|Min|Size|Capacity|NumProcs|Num|Limit|"
                r"MAXRETRIES|MaxRetries|MAX_RETRIES|Bound|Depth|Width|"
                r"NumNodes|NumProc)$", name, re.IGNORECASE):
        return f"CONSTANT {name} = 3"

    # Pattern: used in arithmetic (Name + 1, Name - 1, Name * 2) → numeric
    if re.search(rf"\b{re.escape(name)}\s*[+\-*/]|\b[+\-*/]\s*{re.escape(name)}\b", tla_content):
        return f"CONSTANT {name} = 3"

    # Default: numeric (small number) — safest for TLC enumeration
    return f"CONSTANT {name} = 3"


def _autogenerate_cfg(tla_content: str) -> Optional[str]:
    """
    Heuristically build a minimal .cfg from spec source.

    Looks for:
    - An `Init` operator definition  → INIT Init
    - A `Next` operator definition   → NEXT Next
    - A `TypeOK` invariant           → INVARIANT TypeOK
    - A `Spec` operator              → SPECIFICATION Spec
    - CONSTANT declarations          → assign small model values (context-aware)
    - Fairness needs                  → CHECK_DEADLOCK FALSE if Spec includes fairness

    Returns None if Init and Next are not detectable.
    """
    lines = []

    # Allow indented definitions (some specs indent Init/Next)
    has_init = bool(re.search(r"^\s*Init\s*==", tla_content, re.MULTILINE))
    has_next = bool(re.search(r"^\s*Next\s*==", tla_content, re.MULTILINE))
    has_typeok = bool(re.search(r"^\s*TypeOK\s*==", tla_content, re.MULTILINE))
    has_spec = bool(re.search(r"^\s*Spec\s*==", tla_content, re.MULTILINE))

    if not (has_init and has_next):
        return None

    if has_spec:
        lines.append("SPECIFICATION Spec")
    else:
        lines.append("INIT Init")
        lines.append("NEXT Next")

    # If Spec includes fairness (WF_ or SF_), disable deadlock checking
    # since fair specs deliberately allow stuttering/termination.
    if has_spec and re.search(r"\b[WS]F_", tla_content):
        lines.append("CHECK_DEADLOCK FALSE")

    # Collect invariants: TypeOK + any other *Inv* / Safety* definitions
    invariants = []
    if has_typeok:
        invariants.append("TypeOK")
    for m in re.finditer(r"^\s*(\w+)\s*==", tla_content, re.MULTILINE):
        name = m.group(1)
        if name in ("Init", "Next", "Spec", "TypeOK", "vars", "Terminating"):
            continue
        if re.match(r"(Safety|.*Inv(ariant)?|Mutex|MutualExclusion|Conservation|"
                    r"Bounded|NoOverflow|NoUnderflow|AtMost|NoWrite|Valid|"
                    r".*Conserved|.*Bounded|.*Stable|.*Valid|.*Threshold)", name):
            invariants.append(name)
    if invariants:
        lines.append("INVARIANT " + " ".join(invariants))

    # Auto-assign CONSTANT values using context-aware type inference.
    const_names = _extract_constant_names(tla_content)
    for name in const_names:
        lines.append(_infer_constant_type(name, tla_content))

    return "\n".join(lines) + "\n"
