"""
tlc_validator.py — Wrapper around the TLA+ TLC model checker.

TLC is the primary quality gate for training data.  Running a spec through
TLC and getting no violations makes it "gold tier" — the strongest signal
that the spec is semantically meaningful, not just syntactically valid.

Validation tiers
----------------
gold   — TLC runs to completion with zero violations
silver — SANY parse succeeds but TLC can't run (missing cfg, infinite state, etc.)
bronze — SANY fails (syntactically invalid TLA+); still archived for analysis

.cfg handling
-------------
Many scraped specs lack a companion .cfg file.  TLC requires at minimum:
    INIT  Init
    NEXT  Next
We auto-generate a minimal cfg from common patterns if none is provided.
The auto-generation heuristic looks for `Init` and `Next` definitions and
attempts to add `INVARIANT TypeOK` if a `TypeOK` operator is defined.

Research note
-------------
TLC's exit codes are NOT reliable across versions.  We parse stdout instead:
  - "Model checking completed" with "No error" = gold
  - "Error:" or "Invariant ... is violated" = violation found (still bronze)
  - TLC timeout / state explosion = treated as silver (SANY already passed)
"""

from __future__ import annotations

import re
import subprocess
import tempfile
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

from .sany_validator import validate_file as sany_validate_file, _TLA_TOOLS_JAR

_DEFAULT_JAR = _TLA_TOOLS_JAR
# Default TLC timeout per spec in seconds.  Most well-formed specs finish in <30s.
# Large state-space specs can run forever — we cap them and call it silver.
_TLC_TIMEOUT_S = 60


@dataclass
class SemanticInfo:
    """Semantic quality signals beyond pass/fail."""
    # Coverage: fraction of Next sub-actions that generate at least 1 state
    action_coverage: float = 0.0         # 0.0–1.0; 1.0 = all actions reachable
    total_actions: int = 0
    dead_actions: list[str] = field(default_factory=list)  # action names with 0 states
    # State space
    distinct_states: int = 0
    total_states: int = 0
    # Invariant effectiveness: does the spec actually constrain behaviour?
    invariant_names: list[str] = field(default_factory=list)
    invariants_checked: int = 0          # how many INVARIANTs TLC actually checked
    trivial_invariant: bool = False      # TRUE if invariant is vacuously true (e.g. TRUE, TypeOK on empty state)
    # Mutation test: did weakening the spec change TLC's outcome?
    mutation_tested: bool = False
    mutation_caught: bool = False        # TRUE = invariant caught the mutation → semantically meaningful

    def is_diamond(self) -> bool:
        """Diamond tier: semantically meaningful spec, not just syntactically valid.

        Requires ALL of:
          1. distinct_states > 1    — non-trivial state space (not a single-state spec)
          2. not trivial_invariant  — invariant isn't vacuously TRUE
          3. invariants_checked > 0 — at least one invariant is declared and checked
          4. mutation_caught        — removing invariants changes TLC outcome
                                      (proves invariants actually constrain behavior)

        Notably we do NOT require action_coverage == 1.0: partial coverage
        is fine as long as the spec is semantically constrained.
        """
        return (
            self.distinct_states > 1
            and not self.trivial_invariant
            and self.invariants_checked > 0
            and self.mutation_tested
            and self.mutation_caught
        )


@dataclass
class TLCResult:
    """Full result of a TLC model-check attempt."""
    tier: str                    # "gold" | "silver" | "bronze"
    sany_errors: list[str] = field(default_factory=list)
    tlc_violations: list[str] = field(default_factory=list)
    raw_output: str = ""
    runtime_seconds: float = 0.0
    cfg_was_autogenerated: bool = False
    tla_file: str = ""
    semantic: SemanticInfo = field(default_factory=SemanticInfo)

    @property
    def is_diamond(self) -> bool:
        """True if this spec passes both TLC gold AND the Diamond semantic gate."""
        return self.tier == "gold" and self.semantic.is_diamond()


def validate_file(
    tla_path: Path,
    cfg_path: Optional[Path] = None,
    jar: Path = _DEFAULT_JAR,
    timeout: int = _TLC_TIMEOUT_S,
) -> TLCResult:
    """
    Run TLC on a .tla + optional .cfg file pair.

    Parameters
    ----------
    tla_path : Path            Path to the .tla spec file.
    cfg_path : Path | None     Path to .cfg; auto-generated if None.
    jar      : Path            Path to tla2tools.jar.
    timeout  : int             Seconds before we kill TLC and call it silver.

    Returns
    -------
    TLCResult describing the validation outcome.
    """
    import time

    if not jar.exists():
        raise FileNotFoundError(f"tla2tools.jar not found at {jar}")

    # --- Step 1: SANY check first (fast) ------------------------------------
    sany_result = sany_validate_file(tla_path, jar=jar)
    if not sany_result.valid:
        return TLCResult(
            tier="bronze",
            sany_errors=sany_result.errors,
            raw_output=sany_result.raw_output,
            tla_file=str(tla_path),
        )

    # --- Step 2: Resolve or generate .cfg -----------------------------------
    cfg_was_autogenerated = False
    if cfg_path is None or not cfg_path.exists():
        tla_content = tla_path.read_text(encoding="utf-8", errors="replace")
        cfg_text = _autogenerate_cfg(tla_content)
        if cfg_text is None:
            # Can't even guess Init/Next — return silver (SANY passed)
            return TLCResult(
                tier="silver",
                raw_output="No .cfg and could not auto-generate one (Init/Next not found).",
                tla_file=str(tla_path),
            )
        cfg_was_autogenerated = True
        # Write auto-cfg next to the tla file so TLC can find it
        cfg_path = tla_path.with_suffix(".cfg")
        cfg_path.write_text(cfg_text, encoding="utf-8")

    # --- Step 3: Run TLC ----------------------------------------------------
    cmd = [
        "java", "-cp", str(jar),
        "tlc2.TLC",
        "-config", str(cfg_path),
        str(tla_path),
    ]
    t0 = time.monotonic()
    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=timeout,
            cwd=tla_path.parent,  # TLC resolves EXTENDS relative to cwd
        )
        elapsed = time.monotonic() - t0
        stdout = result.stdout + result.stderr
        violations = _parse_violations(stdout)

        if violations:
            # SANY already passed (step 1); TLC found semantic issues → silver
            tier = "silver"
        elif _detect_success(stdout):
            tier = "gold"
        else:
            # TLC ran but inconclusive (infinite state space, partial check)
            tier = "silver"

        # Compute semantic quality signals for gold specs
        semantic = SemanticInfo()
        if tier == "gold":
            tla_text = tla_path.read_text(encoding="utf-8", errors="replace")
            cfg_text = cfg_path.read_text(encoding="utf-8", errors="replace") if cfg_path else ""
            mod_match = re.search(r"MODULE\s+(\w+)", tla_text)
            mod_name = mod_match.group(1) if mod_match else "Temp"
            try:
                semantic = compute_semantic_info(
                    tla_text, cfg_text, stdout,
                    module_name=mod_name, jar=jar,
                    mutation_timeout=min(timeout, 30),
                )
            except Exception:
                pass  # semantic analysis is best-effort

        return TLCResult(
            tier=tier,
            tlc_violations=violations,
            raw_output=stdout,
            runtime_seconds=elapsed,
            cfg_was_autogenerated=cfg_was_autogenerated,
            tla_file=str(tla_path),
            semantic=semantic,
        )

    except subprocess.TimeoutExpired:
        return TLCResult(
            tier="silver",
            raw_output=f"TLC timed out after {timeout}s (state space likely too large).",
            runtime_seconds=float(timeout),
            cfg_was_autogenerated=cfg_was_autogenerated,
            tla_file=str(tla_path),
        )


def validate_string(
    tla_content: str,
    cfg_content: Optional[str] = None,
    module_name: str = "Temp",
    jar: Path = _DEFAULT_JAR,
    timeout: int = _TLC_TIMEOUT_S,
) -> TLCResult:
    """
    Run TLC on in-memory spec+cfg strings using a temp directory.
    """
    with tempfile.TemporaryDirectory() as tmpdir:
        tmp = Path(tmpdir)
        tla_path = tmp / f"{module_name}.tla"
        tla_path.write_text(tla_content, encoding="utf-8")
        cfg_path = None
        if cfg_content:
            cfg_path = tmp / f"{module_name}.cfg"
            cfg_path.write_text(cfg_content, encoding="utf-8")
        return validate_file(tla_path, cfg_path=cfg_path, jar=jar, timeout=timeout)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _detect_success(output: str) -> bool:
    """TLC prints 'Model checking completed. No error has been found.' on success."""
    return bool(re.search(r"no error has been found", output, re.IGNORECASE))


def _parse_violations(output: str) -> list[str]:
    """Extract violation/error messages from TLC output."""
    violations: list[str] = []
    for line in output.splitlines():
        stripped = line.strip()
        # Skip harmless / success lines
        if re.search(r"(Warning.*garbage collector|Warning.*UseParallelGC)", stripped, re.IGNORECASE):
            continue
        if re.search(r"no error has been found", stripped, re.IGNORECASE):
            continue
        if re.search(r"^(Finished|The depth|The average|calculated)", stripped):
            continue
        if re.search(r"(Invariant|Property|Error|violation|is violated)", stripped, re.IGNORECASE):
            violations.append(stripped)
    return violations


def _parse_coverage(output: str) -> tuple[int, list[str], int]:
    """Parse TLC coverage stats to find dead actions.

    TLC prints lines like:
      <Init line 10, col 1 to line 12, col 20 of module Foo>: 3:3
      <Next line 14, col 1 to line 20, col 30 of module Foo>: 15:100
      <Action1 line 22, col 3 to line 25, col 10 of module Foo>: 0:0

    The format is <name ...>: distinct:total
    An action with 0:0 or 0:N is dead (unreachable from Init via Next).

    Returns (total_actions, dead_action_names, distinct_states).
    """
    total_actions = 0
    dead: list[str] = []
    distinct_states = 0

    for line in output.splitlines():
        # Match coverage lines: <ActionName line ...>: N:M
        m = re.match(r"<(\w+)\s+line\s+\d+.*?>:\s*(\d+):(\d+)", line.strip())
        if m:
            name, distinct_str, total_str = m.group(1), m.group(2), m.group(3)
            if name in ("Init",):
                continue  # Init is always covered
            total_actions += 1
            d = int(distinct_str)
            if d == 0:
                dead.append(name)

    # Parse overall state count
    m = re.search(r"(\d+)\s+distinct\s+state", output)
    if m:
        distinct_states = int(m.group(1))

    return total_actions, dead, distinct_states


def _parse_state_counts(output: str) -> tuple[int, int]:
    """Extract distinct and total state counts from TLC output."""
    distinct = 0
    total = 0
    m = re.search(r"(\d+)\s+distinct\s+state", output)
    if m:
        distinct = int(m.group(1))
    m = re.search(r"(\d+)\s+states?\s+generated", output)
    if m:
        total = int(m.group(1))
    return distinct, total


def _extract_invariant_names(tla_content: str, cfg_content: str = "") -> list[str]:
    """Find invariant names from the cfg and spec."""
    names: list[str] = []
    # From cfg: INVARIANT Foo Bar
    for m in re.finditer(r"INVARIANTS?\s+(.+)", cfg_content):
        for name in re.split(r"\s+", m.group(1).strip()):
            if name and not name.startswith("\\*"):
                names.append(name)
    # Fallback: look for common invariant patterns in spec
    if not names:
        for m in re.finditer(r"^(\w+Inv(?:ariant)?|TypeOK|Safety\w*)\s*==", tla_content, re.MULTILINE):
            names.append(m.group(1))
    return names


def _check_trivial_invariant(tla_content: str, inv_names: list[str]) -> bool:
    """Detect obviously trivial invariants (e.g. 'TypeOK == TRUE')."""
    for name in inv_names:
        m = re.search(rf"^{re.escape(name)}\s*==\s*(.+?)$", tla_content, re.MULTILINE)
        if m:
            body = m.group(1).strip()
            # Trivially true
            if body in ("TRUE", "True", "true"):
                return True
    return False


def _mutation_test(
    tla_content: str,
    cfg_content: str,
    module_name: str,
    jar: Path,
    timeout: int = 30,
) -> tuple[bool, bool]:
    """Run a lightweight mutation test: remove invariants from cfg and re-run TLC.

    If the spec still passes with invariants removed, the invariants weren't
    constraining anything — the spec is syntactically valid but semantically vacuous.

    Returns (tested: bool, caught: bool).
    - tested=True means we ran the mutation
    - caught=True means removing invariants changed the outcome (good — invariants matter)
    """
    # Remove INVARIANT lines from cfg
    mutated_cfg_lines = []
    had_invariants = False
    for line in cfg_content.splitlines():
        if re.match(r"\s*INVARIANTS?\s+", line):
            had_invariants = True
            continue  # skip invariant lines
        mutated_cfg_lines.append(line)

    if not had_invariants:
        return False, False  # no invariants to test

    mutated_cfg = "\n".join(mutated_cfg_lines) + "\n"

    with tempfile.TemporaryDirectory() as tmpdir:
        tmp = Path(tmpdir)
        tla_path = tmp / f"{module_name}.tla"
        cfg_path = tmp / f"{module_name}.cfg"
        tla_path.write_text(tla_content, encoding="utf-8")
        cfg_path.write_text(mutated_cfg, encoding="utf-8")

        cmd = [
            "java", "-cp", str(jar),
            "tlc2.TLC",
            "-config", str(cfg_path),
            str(tla_path),
        ]
        try:
            result = subprocess.run(
                cmd, capture_output=True, text=True, timeout=timeout, cwd=tmp,
            )
            stdout = result.stdout + result.stderr
            # If removing invariants causes violations or changes outcome → invariants matter
            violations = _parse_violations(stdout)
            success = _detect_success(stdout)
            # If it still succeeds without invariants, they weren't doing anything useful.
            # If it fails or finds violations, the invariants were meaningful.
            caught = bool(violations) or not success
            return True, caught
        except (subprocess.TimeoutExpired, Exception):
            return True, False  # couldn't determine


def compute_semantic_info(
    tla_content: str,
    cfg_content: str,
    tlc_output: str,
    module_name: str = "Temp",
    jar: Path = _DEFAULT_JAR,
    run_mutation: bool = True,
    mutation_timeout: int = 30,
) -> SemanticInfo:
    """Compute semantic quality signals from a gold-tier TLC run."""
    info = SemanticInfo()

    # 1. Coverage / reachability
    total_actions, dead_actions, distinct_states = _parse_coverage(tlc_output)
    info.total_actions = total_actions
    info.dead_actions = dead_actions
    info.action_coverage = (
        (total_actions - len(dead_actions)) / total_actions
        if total_actions > 0 else 0.0
    )

    # 2. State space
    info.distinct_states, info.total_states = _parse_state_counts(tlc_output)

    # 3. Invariant analysis
    info.invariant_names = _extract_invariant_names(tla_content, cfg_content)
    info.invariants_checked = len(info.invariant_names)
    info.trivial_invariant = _check_trivial_invariant(tla_content, info.invariant_names)

    # 4. Mutation test (only for gold specs — silver/bronze already failed)
    if run_mutation and info.invariants_checked > 0 and not info.trivial_invariant:
        info.mutation_tested, info.mutation_caught = _mutation_test(
            tla_content, cfg_content, module_name, jar, timeout=mutation_timeout,
        )

    return info


def _autogenerate_cfg(tla_content: str) -> Optional[str]:
    """
    Heuristically build a minimal .cfg from spec source.

    Looks for:
    - An `Init` operator definition  → INIT Init
    - A `Next` operator definition   → NEXT Next
    - A `TypeOK` invariant           → INVARIANT TypeOK
    - A `Spec` operator              → SPECIFICATION Spec
    - CONSTANT declarations          → assign small model values

    Returns None if Init and Next are not detectable.
    """
    lines = []

    has_init = bool(re.search(r"^Init\s*==", tla_content, re.MULTILINE))
    has_next = bool(re.search(r"^Next\s*==", tla_content, re.MULTILINE))
    has_typeok = bool(re.search(r"^TypeOK\s*==", tla_content, re.MULTILINE))
    has_spec = bool(re.search(r"^Spec\s*==", tla_content, re.MULTILINE))

    if not (has_init and has_next):
        return None

    if has_spec:
        lines.append("SPECIFICATION Spec")
    else:
        lines.append("INIT Init")
        lines.append("NEXT Next")

    if has_typeok:
        lines.append("INVARIANT TypeOK")

    # Auto-assign CONSTANT values so TLC can actually run.
    # Use small defaults to keep the state space tractable.
    const_matches = re.findall(r"^CONSTANTS?\s+(.+)$", tla_content, re.MULTILINE)
    for match in const_matches:
        for name in re.split(r"[,\s]+", match.strip()):
            name = name.strip().rstrip(",")
            if not name or name.startswith("(") or name.startswith("\\*"):
                continue
            # Heuristic defaults based on common naming conventions
            if re.match(r"^(N|M|K|MAX|Max|Size|Capacity|NumProcs|Num)$", name):
                lines.append(f"CONSTANT {name} = 3")
            elif re.match(r"^(Proc|Process|Node|Server|Client|Participant)s?$", name):
                lines.append(f"CONSTANT {name} = {{p1, p2, p3}}")
            elif re.match(r"^(Coordinator)$", name):
                lines.append(f"CONSTANT {name} = p0")
            else:
                # Generic: try a small number for unknowns
                lines.append(f"CONSTANT {name} = 3")

    return "\n".join(lines) + "\n"
