"""
tlc_validator.py — Wrapper around the TLA+ TLC model checker.

TLC is the primary quality gate for training data.  Running a spec through
TLC and getting no violations makes it "gold tier" — the strongest signal
that the spec is semantically meaningful, not just syntactically valid.

Validation tiers
----------------
gold   — TLC runs to completion with zero violations
silver — SANY parse succeeds but TLC can't run (missing cfg, infinite state, etc.)
bronze — SANY fails (syntactically invalid TLA+); still archived for analysis

.cfg handling
-------------
Many scraped specs lack a companion .cfg file.  TLC requires at minimum:
    INIT  Init
    NEXT  Next
We auto-generate a minimal cfg from common patterns if none is provided.
The auto-generation heuristic looks for `Init` and `Next` definitions and
attempts to add `INVARIANT TypeOK` if a `TypeOK` operator is defined.

Research note
-------------
TLC's exit codes are NOT reliable across versions.  We parse stdout instead:
  - "Model checking completed" with "No error" = gold
  - "Error:" or "Invariant ... is violated" = violation found (still bronze)
  - TLC timeout / state explosion = treated as silver (SANY already passed)
"""

from __future__ import annotations

import re
import subprocess
import tempfile
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

from .sany_validator import validate_file as sany_validate_file, _TLA_TOOLS_JAR

_DEFAULT_JAR = _TLA_TOOLS_JAR
# Default TLC timeout per spec in seconds.  Most well-formed specs finish in <30s.
# Large state-space specs can run forever — we cap them and call it silver.
_TLC_TIMEOUT_S = 60


@dataclass
class TLCResult:
    """Full result of a TLC model-check attempt."""
    tier: str                    # "gold" | "silver" | "bronze"
    sany_errors: list[str] = field(default_factory=list)
    tlc_violations: list[str] = field(default_factory=list)
    raw_output: str = ""
    runtime_seconds: float = 0.0
    cfg_was_autogenerated: bool = False
    tla_file: str = ""


def validate_file(
    tla_path: Path,
    cfg_path: Optional[Path] = None,
    jar: Path = _DEFAULT_JAR,
    timeout: int = _TLC_TIMEOUT_S,
) -> TLCResult:
    """
    Run TLC on a .tla + optional .cfg file pair.

    Parameters
    ----------
    tla_path : Path            Path to the .tla spec file.
    cfg_path : Path | None     Path to .cfg; auto-generated if None.
    jar      : Path            Path to tla2tools.jar.
    timeout  : int             Seconds before we kill TLC and call it silver.

    Returns
    -------
    TLCResult describing the validation outcome.
    """
    import time

    if not jar.exists():
        raise FileNotFoundError(f"tla2tools.jar not found at {jar}")

    # --- Step 1: SANY check first (fast) ------------------------------------
    sany_result = sany_validate_file(tla_path, jar=jar)
    if not sany_result.valid:
        return TLCResult(
            tier="bronze",
            sany_errors=sany_result.errors,
            raw_output=sany_result.raw_output,
            tla_file=str(tla_path),
        )

    # --- Step 2: Resolve or generate .cfg -----------------------------------
    cfg_was_autogenerated = False
    if cfg_path is None or not cfg_path.exists():
        tla_content = tla_path.read_text(encoding="utf-8", errors="replace")
        cfg_text = _autogenerate_cfg(tla_content)
        if cfg_text is None:
            # Can't even guess Init/Next — return silver (SANY passed)
            return TLCResult(
                tier="silver",
                raw_output="No .cfg and could not auto-generate one (Init/Next not found).",
                tla_file=str(tla_path),
            )
        cfg_was_autogenerated = True
        # Write auto-cfg next to the tla file so TLC can find it
        cfg_path = tla_path.with_suffix(".cfg")
        cfg_path.write_text(cfg_text, encoding="utf-8")

    # --- Step 3: Run TLC ----------------------------------------------------
    cmd = [
        "java", "-cp", str(jar),
        "tlc2.TLC",
        "-config", str(cfg_path),
        str(tla_path),
    ]
    t0 = time.monotonic()
    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=timeout,
            cwd=tla_path.parent,  # TLC resolves EXTENDS relative to cwd
        )
        elapsed = time.monotonic() - t0
        stdout = result.stdout + result.stderr
        violations = _parse_violations(stdout)

        if violations:
            # SANY already passed (step 1); TLC found semantic issues → silver
            tier = "silver"
        elif _detect_success(stdout):
            tier = "gold"
        else:
            # TLC ran but inconclusive (infinite state space, partial check)
            tier = "silver"

        return TLCResult(
            tier=tier,
            tlc_violations=violations,
            raw_output=stdout,
            runtime_seconds=elapsed,
            cfg_was_autogenerated=cfg_was_autogenerated,
            tla_file=str(tla_path),
        )

    except subprocess.TimeoutExpired:
        return TLCResult(
            tier="silver",
            raw_output=f"TLC timed out after {timeout}s (state space likely too large).",
            runtime_seconds=float(timeout),
            cfg_was_autogenerated=cfg_was_autogenerated,
            tla_file=str(tla_path),
        )


def validate_string(
    tla_content: str,
    cfg_content: Optional[str] = None,
    module_name: str = "Temp",
    jar: Path = _DEFAULT_JAR,
    timeout: int = _TLC_TIMEOUT_S,
) -> TLCResult:
    """
    Run TLC on in-memory spec+cfg strings using a temp directory.
    """
    with tempfile.TemporaryDirectory() as tmpdir:
        tmp = Path(tmpdir)
        tla_path = tmp / f"{module_name}.tla"
        tla_path.write_text(tla_content, encoding="utf-8")
        cfg_path = None
        if cfg_content:
            cfg_path = tmp / f"{module_name}.cfg"
            cfg_path.write_text(cfg_content, encoding="utf-8")
        return validate_file(tla_path, cfg_path=cfg_path, jar=jar, timeout=timeout)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _detect_success(output: str) -> bool:
    """TLC prints 'Model checking completed. No error has been found.' on success."""
    return bool(re.search(r"no error has been found", output, re.IGNORECASE))


def _parse_violations(output: str) -> list[str]:
    """Extract violation/error messages from TLC output."""
    violations: list[str] = []
    for line in output.splitlines():
        stripped = line.strip()
        # Skip harmless / success lines
        if re.search(r"(Warning.*garbage collector|Warning.*UseParallelGC)", stripped, re.IGNORECASE):
            continue
        if re.search(r"no error has been found", stripped, re.IGNORECASE):
            continue
        if re.search(r"^(Finished|The depth|The average|calculated)", stripped):
            continue
        if re.search(r"(Invariant|Property|Error|violation|is violated)", stripped, re.IGNORECASE):
            violations.append(stripped)
    return violations


def _autogenerate_cfg(tla_content: str) -> Optional[str]:
    """
    Heuristically build a minimal .cfg from spec source.

    Looks for:
    - An `Init` operator definition  → INIT Init
    - A `Next` operator definition   → NEXT Next
    - A `TypeOK` invariant           → INVARIANT TypeOK
    - A `Spec` operator              → SPECIFICATION Spec
    - CONSTANT declarations          → assign small model values

    Returns None if Init and Next are not detectable.
    """
    lines = []

    has_init = bool(re.search(r"^Init\s*==", tla_content, re.MULTILINE))
    has_next = bool(re.search(r"^Next\s*==", tla_content, re.MULTILINE))
    has_typeok = bool(re.search(r"^TypeOK\s*==", tla_content, re.MULTILINE))
    has_spec = bool(re.search(r"^Spec\s*==", tla_content, re.MULTILINE))

    if not (has_init and has_next):
        return None

    if has_spec:
        lines.append("SPECIFICATION Spec")
    else:
        lines.append("INIT Init")
        lines.append("NEXT Next")

    if has_typeok:
        lines.append("INVARIANT TypeOK")

    # Auto-assign CONSTANT values so TLC can actually run.
    # Use small defaults to keep the state space tractable.
    const_matches = re.findall(r"^CONSTANTS?\s+(.+)$", tla_content, re.MULTILINE)
    for match in const_matches:
        for name in re.split(r"[,\s]+", match.strip()):
            name = name.strip().rstrip(",")
            if not name or name.startswith("(") or name.startswith("\\*"):
                continue
            # Heuristic defaults based on common naming conventions
            if re.match(r"^(N|M|K|MAX|Max|Size|Capacity|NumProcs|Num)$", name):
                lines.append(f"CONSTANT {name} = 3")
            elif re.match(r"^(Proc|Process|Node|Server|Client|Participant)s?$", name):
                lines.append(f"CONSTANT {name} = {{p1, p2, p3}}")
            elif re.match(r"^(Coordinator)$", name):
                lines.append(f"CONSTANT {name} = p0")
            else:
                # Generic: try a small number for unknowns
                lines.append(f"CONSTANT {name} = 3")

    return "\n".join(lines) + "\n"
